services:
  postgres:
    image: postgres:16-alpine
    container_name: rplan-db-prod
    environment:
      POSTGRES_USER: ${PG_RPLAN_USER}
      POSTGRES_PASSWORD: ${PG_RPLAN_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_RPLAN_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    container_name: rplan-migrate-prod
    build:
      dockerfile: ./packages/database/Dockerfile.prod
    depends_on:
      postgres:
        condition: service_started
    networks:
      - rplan-network
    environment:
      PG_URL: postgresql://${PG_RPLAN_USER}:${PG_RPLAN_PASSWORD}@postgres:5432/${PG_DB}
  backend:
    container_name: rplan-backen-prod
    build:
      dockerfile: ./apps/backend/Dockerfile.prod
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "4010:4000"
    environment:
      NODE_ENV: production
      PG_URL: postgresql://${PG_RPLAN_USER}:${PG_RPLAN_PASSWORD}@postgres:5432/${PG_DB}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_AUTH_USER: ${SMTP_AUTH_USER}
      SMTP_AUTH_PASS: ${SMTP_AUTH_PASS}
      SALT_ROUNDS: ${SALT_ROUNDS}
      PASSWORD_FORGOTTEN_SECRET_KEY: ${PASSWORD_FORGOTTEN_SECRET_KEY}
      EMAIL_VALIDATION_SECRET_KEY: ${EMAIL_VALIDATION_SECRET_KEY}
      TOKEN_PASSWORD_FORGOTTEN_EXPIRATION: ${TOKEN_PASSWORD_FORGOTTEN_EXPIRATION}
      COOKIE_AUTH_NAME: ${COOKIE_AUTH_NAME}
      COOKIE_AUTH_EXPIRATION: ${COOKIE_AUTH_EXPIRATION}
      AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
      COOKIE_REFRESH_NAME: ${COOKIE_REFRESH_NAME}
      COOKIE_REFRESH_EXPIRATION: ${COOKIE_REFRESH_EXPIRATION}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}

  frontend:
    container_name: rplan-frontend-prod
    build:
      dockerfile: ./apps/frontend/Dockerfile.prod
    depends_on:
      backend:
        condition: service_started
    ports:
      - "4000:3000"

  maildev:
    image: maildev/maildev:2.1.0
    container_name: rplan-maildev-dev
    ports:
      - "4020:1080"
      - "4025:1025"

volumes:
  pgdata:

networks:
  rplan-network:
    driver: bridge
